name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Hello world
      run: ls
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: alefaure/gitlab-ci-android
        tags: ${{ secrets.DOCKER_TAG_VERSION }}
        dockerfile: $GITHUB_WORKSPACE/Dockerfile
